[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pentest-tools"
version = "0.1.0"
description = "My own useful tools for pentesting"
authors = [
    {name = "Wille Johnsson", email = "wille.johnsson@iths.se"}
]
license = {file = "LICENSE"}
dependencies = [
    "argparse",
    "click",
    "typer"
]
classifiers = [
    # Classifiers
]

[project.entry-points.console_scripts]
hello = "hello_world.main:main"
